# ---------- Build stage ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.sln .
COPY BLL/*.csproj BLL/
COPY DAL/*.csproj DAL/
COPY *.csproj ./

RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o out

# ---------- Runtime stage ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Production

COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "GameCompetionAnalysisSystem.dll"]
